logging:
  level:
    com:
      hanssecurity: DEBUG
    org:
      springframework:
        security: DEBUG
        jdbc:
          core: TRACE
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}
              %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    hikari:
      auto-commit: false
      data-source-properties:
        # 缓存 SQL 语句
        cachePrepStmts: true
        # 缓存大小
        prepStmtCacheSize: 250
        # 缓存 SQL 的长度限制
        prepStmtCacheSqlLimit: 2048
        # 服务器预编译
        useServerPrepStmts: true
      pool-name: Hikari
    type: com.zaxxer.hikari.HikariDataSource
    # 数据库连接 URL
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    # 数据库用户名
    username: user
    # 数据库密码
    password: password
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        generate_statistics: false
        id:
          new_generator_mappings: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
    show-sql: true
  ldap:
    base: dc=imooc,dc=com
    embedded:
      base-dn: dc=imooc,dc=com
      ldif: classpath:test-ldap-server.ldif
      port: 8389
    urls: ldap://localhost:8389/

  profiles: dev