logging:
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}
              %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'
hans:
  jwt:
    access-token-expire-time: 300000
    header: Authorization
    prefix: "Bearer "
    refresh-token-expire-time: 2592000000
    key: ${JWT_KEY}
    refresh-key: ${JWT_REFRESH_KEY}
  ali:
    api-key: ${ALI_API_KEY}
    api-sercrt: ${ALI_API_SECRET}
  sms-provider:
    name: ali
  email-provider:
    api-key: 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
    name: api

server:
  error:
    whitelabel:
      enabled: true
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: uaa
  # i18n
#  cache:
#    type: redis
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password: mypass
#    timeout: 60000
  datasource:
    initialization-mode: embedded
  mail:
    host: smtp.sendgrid.net
    password: apikey
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: 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
  messages:
    always-use-message-format: false
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: "@spring.profiles.active@"
  redis:
    host: localhost
    port: 6379
    password: mypass
  resources:
    add-mappings: true



#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}


#  security:
#    user:
#      name: user
#      password: 12345678
#      roles: USER, ADMIN

