logging:
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}
              %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'
server:
  error:
    whitelabel:
      enabled: true
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: uaa
  # i18n
  messages:
    always-use-message-format: false
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false
  datasource:
    initialization-mode: embedded
  profiles:
    active: "@spring.profiles.active@"
  resources:
    add-mappings: false
hans:
  jwt:
    access-token-expire-time: 300000
    header: Authorization
    prefix: "Bearer "
    refresh-token-expire-time: 2592000000
  ali:
    api-key: ${ALI_API_KEY}
    api-sercrt: ${ALI_API_SECRET}
  sms-provider:
    name: ali
  email-provider:
    api-key: ${EMAIL_API_KEYj}
    name: api
  mail:
    host: ${SMTP_HOST}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${SMTP_USERNAME}


#  security:
#    user:
#      name: user
#      password: 12345678
#      roles: USER, ADMIN

